### ISSUE TITLE
set terminal png

### ISSUE THREAD

**Issue by jtrmal** [usnistgov/F4DE#1]
The options f4de generates for gnuplot assume the png terminal will be provided by libgd.
When png terminal is provided by libcairo, this command from the makefile will ends up with an error:

```
gnuplot> set terminal png truecolor medium size 800,800 crop
Terminal type set to 'pngcairo'
                                    ^
         unrecognized terminal option
```

**Comment by mmartial** [comment]
which linux distribution are you using ?

**Comment by jtrmal** [comment]
$ cat /etc/*-release
CentOS release 6.7 (Final)
Cluster Manager v7.1
slave
LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
CentOS release 6.7 (Final)
CentOS release 6.7 (Final)

We have gnuplot provided via the "modules" so I'm not sure if the gnuplot
is from the distribution
$  gnuplot --version
gnuplot 5.0 patchlevel 0

**Comment by mmartial** [comment]
I will test it using a CentOS 6.7 VM, in the meanwhile if you can use a docker, look at https://hub.docker.com/r/martialnist/docker-f4de/

**Comment by jtrmal** [comment]
I actually gave up and installed  my own gnuplot -- for a user having no
control about the OS or the packages,this was probably the most
straightforward path.
y.

**Comment by jtrmal** [comment]
I actually think that even an error message would be fine, assuming it
would be to the point:

Error: gnuplot binary exists but the png terminal is not supported
and
Error: gnuplot binary exists but the png terminal does not support the
necessary options (you probably have libcairo png terminal instead of libgd
png term)

or something like that.
y.

**Comment by mmartial** [comment]
One thing I am unclear is that the terminal type should have been 'pngcairo' (not png). I have added a check for libgd's PNG support in the `make mincheck` which should now exit with error unless it is installed and available to gnuplot.

**Comment by jfiscus** [comment]
Pngcairo was a more function png library.

**Comment by jtrmal** [comment]
My impression was that if libgd png teminal will not get compiled in, an
alias (or a compatibility layer) will be created using libcairo to act as
"png" terminal as well (in addition to pngcairo). However, for some reason
it does not support the "medium" keyword (IIRC).
y.

**Comment by mmartial** [comment]
Just as a follow up, as I have been trying on CentOS 6.7, if you `yum install gd gd-dev` before doing the `yum install gnuplot`, when you run `echo 'set terminal' | gnuplot` you will see a _png_ line such that `PNG images using libgd and TrueType fonts` (ie no more dependency on libcairo).

**Comment by LJHIndustries** [comment]
I had the same issue where png was not being recognized, I installed libgd (below) and then gnuplot again from source:

yum install gd-devel
