### ISSUE TITLE
F4DE install procedure

### ISSUE THREAD

**Issue by jtrmal** [usnistgov/F4DE#2]
The F4DE install procedure is extremely complicated even for a fairly experienced perl programmer in case the programmer does not have a root access to install the packages.
Perhaps this process could be much more streamlined by using local::lib module (and install the modules F4DE-locally) or at least document this procedure.

**Comment by mmartial** [comment]
For a non root user, I understand the difficulty. The 'make perl_install' (which uses cpanp) listed in the README is designed for a user having control over his system.
If that is not the case and 'docker' is available, we have a docker version available as 'martialnist/docker-f4de'. Another option is to use perlbrew to install a user directory installation of Perl.
That said I will look into adding a local::lib option if possible.

**Comment by mmartial** [comment]
I have extended the `README.md` to include the _perlbrew_ and _docker_ information, hoping that this will make it easier for most people. We are not discarding `local::lib`, but it is not supported in this version yet.
