### ISSUE TITLE
Tests Failing for Perl 5.26.1, 5.24.1, 5.20.0 Specifically Error!!! OPTIMUMCOMB computation failed for attribute MMISS

### ISSUE THREAD

**Issue by nelaturuharsha** [usnistgov/F4DE#7]
I ran the make perl_install with several versions of perl
Namely 

1. 5.26.1
2. 5.24.1
3. 5.20.0 

When running make check

The following error is shown : 
Error!!! OPTIMUMCOMB computation failed for attribute MMISS but expected 0.8555, got 
$VAR1 = {
          'MMISS' => undef,
          'DETECTIONSCORE' => undef,
          'MFA' => undef,
          'BLOCKS' => {},
          'COMB' => undef
        };
Makefile:11: recipe for target 'check' failed
make[3]: *** [check] Error 1
make[3]: Leaving directory '/home/harsha/speech-tf-1.13-kaldi/F4DE/common/test'
Makefile:272: recipe for target 'commoncheck' failed
make[2]: *** [commoncheck] Error 2
make[2]: Leaving directory '/home/harsha/speech-tf-1.13-kaldi/F4DE'
Makefile:255: recipe for target 'mincheck' failed
make[1]: *** [mincheck] Error 2
make[1]: Leaving directory '/home/harsha/speech-tf-1.13-kaldi/F4DE'
Makefile:259: recipe for target 'check' failed
make: *** [check] Error 2

**Comment by SreeHarshaNelaturu** [comment]
> I ran the make perl_install with several versions of perl
> Namely
> 
> 1. 5.26.1
> 2. 5.24.1
> 3. 5.20.0
> 
> When running make check
> 
> The following error is shown :
> Error!!! OPTIMUMCOMB computation failed for attribute MMISS but expected 0.8555, got
> $VAR1 = {
> 'MMISS' => undef,
> 'DETECTIONSCORE' => undef,
> 'MFA' => undef,
> 'BLOCKS' => {},
> 'COMB' => undef
> };
> Makefile:11: recipe for target 'check' failed
> make[3]: *** [check] Error 1
> make[3]: Leaving directory '/home/harsha/speech-tf-1.13-kaldi/F4DE/common/test'
> Makefile:272: recipe for target 'commoncheck' failed
> make[2]: *** [commoncheck] Error 2
> make[2]: Leaving directory '/home/harsha/speech-tf-1.13-kaldi/F4DE'
> Makefile:255: recipe for target 'mincheck' failed
> make[1]: *** [mincheck] Error 2
> make[1]: Leaving directory '/home/harsha/speech-tf-1.13-kaldi/F4DE'
> Makefile:259: recipe for target 'check' failed
> make: *** [check] Error 2
